spring.application.name=debris-tracker
#Eger MySql üzerinden bir veritaban? ba?lant?s? yap?lmak istenirse kullan?lmas? gereken kodlar bunlar
# Database Ayarlari
spring.datasource.url=jdbc:mysql://localhost:3306/######?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=#######
spring.jpa.hibernate.ddl-auto=update

spring.jpa.properties.hibernate.format_sql=true
spring.jpa.show-sql=true